---
- name: Add ansible repo to sources and ansible key to key server
  become: true
  shell: "{{ item }}"
  with_items:
    - echo  "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" > /etc/apt/sources.list.d/ansible.list
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367

- name: Install ansible
  become: true
  apt:
    name: ['python3','python3-boto','python3-boto3','ansible']
    state: present      
    update_cache: yes

- name: Clone ansible git repo
  become: true
  git:
    repo: "https://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@github.com/AngelosKatsantonis/{{ ansible_repo }}"
    dest: ~/ansible
    clone: yes

- name: Create directory to store aws creds
  become: true
  file:
    path: "/root/.aws"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy aws creds
  become: true
  copy:
    src: "templates/awscreds.sh"
    dest: "/root/.aws/awscreds.sh"
    owner: root
    group: root
    mode: '0755'
