- hosts: tag_Name_{{ ec2_tag_Name }} 
  gather_facts: true
  user: admin
  tasks:
    - include_role:
        name: copy_key
    - include_role:
        name: configure_server_commons
    - include_role:
        name: setup_ansible    
    - include_role:
        name: setup_unbound    
    - include_role:
        name: setup_docker    
    - include_role:
        name: manage_ec2_instance    
      vars:
        ec2_state: "restarted"
